openapi: 3.0.0
info:
  title: Swagger Template API
  description: Swagger Template API 定義書
  version: 0.0.1
tags:
  - name: 企業
    description: 企業管理 REST API
  - name: セッション
    description: セッション管理 REST API
paths:
  /companies:
    get:
      tags:
        - 企業
      summary: 企業一覧取得
      description: 企業の一覧取得
      parameters:
        - name: session_token
          in: cookie
          required: true
          description: セッショントークン
          schema:
            type: string
            minimum: 1
      responses:
        '200':
          description: |
            OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items: &ref_0
                      type: object
                      title: 企業情報
                      properties:
                        companyId:
                          description: 企業ID
                          type: string
                          example: '34285'
                        companyName:
                          description: 企業名
                          type: string
                          example: ヤマト運輸株式会社
                        auditInfo:
                          type: object
                          title: 監査情報
                          properties:
                            createdAt:
                              description: 登録日時
                              type: string
                              example: '2021-01-01T00:00:00Z'
                            createdBy:
                              description: 登録者ID
                              type: integer
                              example: 101
                            updatedAt:
                              description: 更新日時
                              type: string
                              example: '2021-01-01T00:00:00Z'
                            updatedBy:
                              description: 更新者ID
                              type: integer
                              example: 101
                  count:
                    description: 全データの件数
                    type: integer
                    example: 1
        '401': &ref_1
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                title: 401 Unauthorized
                description: 401 Unauthorized エラーレスポンス
                required:
                  - code
                properties:
                  code:
                    type: string
                    title: エラーコード
                    enum:
                      - E401000
                    example: E401000
                    description: |
                      開発者向けのエラーコード

                      ```
                      E401000:
                        リクエストに権限がないことを表すエラーコードです。
                      ```
                  message:
                    type: string
                    title: エラーメッセージ
                    description: 開発者向けのエラーメッセージ
                    example: Unauthorized
              example:
                code: E401000
                mesasge: Unauthorized
        '404': &ref_2
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                title: 400 Bad Request
                description: 400 Bad Request エラーレスポンス
                required:
                  - code
                properties:
                  code:
                    type: string
                    title: エラーコード
                    enum:
                      - E400000
                    example: E400000
                    description: |
                      開発者向けのエラーコード

                      ```
                      E400000:
                        リクエストのパラメータに不正が存在することを表すエラーコードです。
                      ```
                  message:
                    type: string
                    title: エラーメッセージ
                    description: 開発者向けのエラーメッセージ
                    example: Invalid Parameter
              example:
                code: E400000
                mesasge: Invalid Parameter
        '500': &ref_3
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                title: 500 Internal Server Error
                description: 500 Internal Server Error エラーレスポンス
                required:
                  - code
                properties:
                  code:
                    type: string
                    title: エラーコード
                    enum:
                      - E500000
                    example: E500000
                    description: |
                      開発者向けのエラーコード

                      ```
                      E500000:
                        サーバーにてエラーが発生したことを表すエラーコードです。
                      ```
                  message:
                    type: string
                    title: エラーメッセージ
                    description: 開発者向けのエラーメッセージ
                    example: Internal Server Error
              example:
                code: E500000
                mesasge: Internal Server Error
  '/companies/{id}':
    put:
      tags:
        - 企業
      summary: 企業更新
      description: 企業の更新
      parameters:
        - name: id
          in: path
          required: true
          description: 企業ID
          schema:
            type: string
        - name: session_token
          in: cookie
          required: true
          description: セッショントークン
          schema:
            type: string
            minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              title: 企業情報更新リクエスト
              description: 企業情報更新のリクエスト
              properties:
                companyName:
                  title: 企業名
                  type: string
                  description: |
                    企業名
                  example: 佐川急便株式会社
      responses:
        '200':
          description: |
            企業情報の更新に成功した時
          content:
            application/json:
              schema: *ref_0
        '400': &ref_4
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                title: 400 Bad Request
                description: 400 Bad Request エラーレスポンス
                required:
                  - code
                properties:
                  code:
                    type: string
                    title: エラーコード
                    enum:
                      - E400000
                    example: E400000
                    description: |
                      開発者向けのエラーコード

                      ```
                      E400000:
                        リクエストのパラメータに不正が存在することを表すエラーコードです。
                      ```
                  message:
                    type: string
                    title: エラーメッセージ
                    description: 開発者向けのエラーメッセージ
                    example: Invalid Parameter
              example:
                code: E400000
                mesasge: Invalid Parameter
        '401': *ref_1
        '404': *ref_2
        '500': *ref_3
    delete:
      tags:
        - 企業
      summary: 企業削除
      description: 企業の削除
      parameters:
        - name: id
          in: path
          required: true
          description: 企業ID
          schema:
            type: integer
        - name: session_token
          in: cookie
          required: true
          description: セッショントークン
          schema:
            type: string
            minimum: 1
      responses:
        '204':
          description: |
            No Content
        '400': *ref_4
        '401': *ref_1
        '404': *ref_2
        '500': *ref_3
  /sessions:
    post:
      tags:
        - セッション
      summary: ログイン
      description: ログイン
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              title: ログインリクエスト
              description: ログインリクエスト
              required:
                - email
                - password
              properties:
                email:
                  title: メールアドレス
                  type: string
                  description: |
                    メールアドレス
                  example: suzuki.taro123@example.com
                password:
                  title: パスワード
                  type: string
                  description: |
                    パスワード
                  example: p@ssw0rd
      responses:
        '201':
          description: |
            CREATED
          headers:
            session_token:
              description: セッショントークン
              schema:
                type: string
        '400': *ref_4
        '404': *ref_2
        '500': *ref_3
    delete:
      tags:
        - セッション
      summary: ログアウト
      description: イメージの一覧取得
      parameters:
        - name: session_token
          in: cookie
          required: true
          description: セッショントークン
          schema:
            type: string
            minimum: 1
      responses:
        '204':
          description: |
            OK
        '500': *ref_3
