import {
  IconArrowLeft,
  IconBrandFacebook,
  IconBrandInstagram,
  IconBrandTiktok,
  IconBrandTwitter,
  IconBrandYoutube,
  IconDotsCircleHorizontal,
  IconHeart,
  IconLink,
  IconSearch,
  IconShoppingCart,
  IconShoppingCartPlus,
  IconToolsKitchen2,
  IconX,
} from '@tabler/icons-react';
import { ChefHat, Settings } from 'lucide-react';

export const Icons = {
  Search: IconSearch,
  Fav: IconHeart,
  Cart: IconShoppingCart,
  CartPlus: IconShoppingCartPlus,
  Chef: ChefHat,
  Setting: Settings,
  XButton: IconX,
  ToolsKitchen2: IconToolsKitchen2,
  BackArrow: IconArrowLeft,
  Youtube: IconBrandYoutube,
  Instagram: IconBrandInstagram,
  TikTok: IconBrandTiktok,
  Twitter: IconBrandTwitter,
  Facebook: IconBrandFacebook,
  OtherLink: IconLink,
  Detail: IconDotsCircleHorizontal,
};
